### ISSUE TITLE
Repo is empty- Follow up on BIBM paper

### ISSUE THREAD

**Issue by azzaea** [CNRGH/WMS-benchmark#1]
Hello!
I'm redirected to this repo based on the paper: "Evaluating Workflow Management Systems: A Bioinformatics Use Case".

Figure 2 in your manuscript is really cool, but hard to navigate through; and it doesn't help that Table 2 shows no units of measurement. Would you be amenable to share raw data used for both the table and figure? Also, can I ask how you did your benchmarking in a cluster? 

Thanks,
Azza

**Comment by bioinfornatics** [comment]
Thanks, @azzaea for your interest on this work.
Our team is working on this issue. 
This repo will be updated soon.

You can keep in touch in the future. 

Best regards

**Comment by azzaea** [comment]
Glad to have heard back from you @bioinfornatics ! Can I also ask about what tools you used for measuring those parameters reported? Would be great if you shared that too.

Thanks in advance,
Azza

**Comment by azzaea** [comment]
Hello again @bioinfornatics ,
Wondering if there are updates on this front?
Thanks

**Comment by bioinfornatics** [comment]
Hi @azzaea , I know that @elarsonneur is working on with some continuous integration to facilitate your usage.

Best regards

**Comment by elarsonneur** [comment]
Hello @azzaea,

The repository is now updated. 
You will find the table with values in [figures](https://github.com/CNRGH/WMS-benchmark/tree/master/figures)  directory.
Please see the README.md file to know how to run the benchmark on one cluster node.

Regards,
Elise
